Add statistics page to the robot gui
introlab/opentera-webrtc-ros pull request #58
Opened 2022-10-27 13:45 UTC by joli-1801

2022-10-27 16:51 UTC, doumdi approved these changes
@joli-1801 Can you ensure C++ style is correct in all GUI files please using https://github.com/introlab/opentera-webrtc-ros/blob/main/.clang-format.

2022-10-28 12:00 UTC, doumdi approved these changes

2022-10-28 17:11 UTC, philippewarren requested changes

2022-10-28 17:11 UTC, philippewarren commented on opentera_webrtc_robot_gui/src/MainWindow.cpp
> +        newIcon.addFile(":/battery-empty.png");
This will only happen if batteryLevel is bigger than 100%?

2022-10-28 17:11 UTC, philippewarren commented on opentera_webrtc_robot_gui/src/MainWindow.cpp
> +    if (wifiStrength == 0)
This compares `float`s using `==`. Is it a pure zero when we want this check to succeed?

2022-10-28 17:11 UTC, philippewarren commented on opentera_webrtc_robot_gui/src/Statistics.cpp
> +    for (i = list.begin(); i != list.end(); i++)
Use range-for loop

2022-10-31 13:04 UTC, joli-1801 commented on opentera_webrtc_robot_gui/src/MainWindow.cpp
> +        newIcon.addFile(":/battery-empty.png");
Yes, it was suppose to indicate an incorrect battery value, but I'll adjust it to include negative values, so that everything that's not in the 0-100 range gets this icon

2022-10-31 13:20 UTC, joli-1801 commented on opentera_webrtc_robot_gui/src/MainWindow.cpp
> +    if (wifiStrength == 0)
No, I'll broaden it to take into account a 0.1 error

2022-10-31 17:17 UTC, philippewarren approved these changes

2022-10-31 17:57 UTC, doumdi approved these changes

2022-10-31 17:57 UTC, merged