Add face_following package and demo
introlab/opentera-webrtc-ros pull request #60
Opened 2022-11-09 19:04 UTC by joli-1801

2022-11-10 16:48 UTC, philippewarren requested changes

2022-11-10 16:48 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +    image_transport::ImageTransport it(m_nodeHandle);
This is local to the constructor, this works?

2022-11-10 16:48 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +        if (ceilf(newHeight) / floorf(newHeight) == 1.0)
Comparing floats using `==` is error-prone

2022-11-10 16:48 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +        if (ceilf(newWidth) / floorf(newWidth) == 1.0)
Comparing floats using `==` is error-prone

2022-11-10 16:48 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +    while (ceilf(n2 / b) / floorf(n2 / b) != 1.0)
Comparing floats using `==` is error-prone

2022-11-10 16:48 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +    while (ceilf(n1 / b) / floorf(n1 / b) != 1.0)
Comparing floats using `==` is error-prone

2022-11-10 16:48 UTC, philippewarren commented on face_cropping/src/Parameters.cpp
> +}
No need for a namespace, you are in a cpp file.
Use a static function instead

2022-11-10 16:48 UTC, philippewarren commented on face_cropping/src/main.cpp
> +    }
Use `ros::spin` in combination with `ros::Timer` for a more precise timing of the important part of the code.

2022-11-10 16:48 UTC, philippewarren commented on opentera_webrtc_demos/launch/opentera_demo.launch
> +    <!-- face follower local -->
Use a capital first letter for consistency.
Use `cropper` (forgot that one)

2022-11-10 16:48 UTC, philippewarren commented on opentera_webrtc_demos/launch/opentera_demo.launch
> +    <!-- face follower webrtc -->
Use a capital first letter for consistency.
Use `cropper` (forgot that one)

2022-11-10 16:48 UTC, philippewarren commented on opentera_webrtc_demos/launch/opentera_demo.launch
> +        <param name="cv_cap_prop_fps" type="double" value="30"/>
This is unreliable: setting the framerate to a value that is not supported by the webcam will fail silently.

2022-11-10 18:42 UTC, joli-1801 commented on face_cropping/src/FaceCropper.cpp
> +    image_transport::ImageTransport it(m_nodeHandle);
Yes it works, it seems that for ImageTransport there's no need to make it global if the publishers and subscribers are, should I still make it global for consistency with the nodeHandle?

2022-11-10 22:11 UTC, joli-1801 commented on face_cropping/src/main.cpp
> +    }
Using `ros::spin()` would a `ros::TImer() `be usefull since I woudn't do anything in the callback? Should I use a `ros::Timer` that calls `ros::spinOnce` in the callback instead or just use `ros::spin() `without the timer?

2022-11-11 13:32 UTC, doumdi commented on face_following/include/face_following/FaceFollower.h
> +        int getGCD(int num, int den);
Would prefer in a utils header if reused. Otherwise private would do the job.

2022-11-11 15:51 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +    image_transport::ImageTransport it(m_nodeHandle);
I would do it so that we don't rely on this behaviour as it could be an implementation detail, and also for consistency

2022-11-11 15:55 UTC, philippewarren commented on face_cropping/src/main.cpp
> +    }
In fact, you can probably just use `ros::spin` (which will block forever), and rely on the frequency of the topic to which you are subscribed.

2022-11-14 14:20 UTC, joli-1801 commented on face_following/include/face_following/FaceFollower.h
> +        int getGCD(int num, int den);
They weren't reused but I still ended up making a utils header for consistency with other packages and it'll already be done in the event that we need to reuse them

2022-11-14 14:27 UTC, joli-1801 commented on opentera_webrtc_demos/launch/opentera_demo.launch
> +        <param name="cv_cap_prop_fps" type="double" value="30"/>
I just removed them, it matches other uses of cv_camera and it still works

2022-11-14 17:03 UTC, philippewarren requested changes

2022-11-30 14:13 UTC, doumdi requested changes

2022-11-30 14:13 UTC, doumdi commented on face_cropping/README.md
> +# face_cropping
@joli-1801 Add "enabled" documentation.

2022-11-30 14:49 UTC, philippewarren requested changes

2022-11-30 14:49 UTC, philippewarren commented on face_cropping/include/face_cropping/FaceCropper.h
> +    using detectionVector = std::vector<std::tuple<int, std::vector<std::tuple<int, cv::Rect>>>>;
Start name of types with a capital letter `DetectionVector`

2022-11-30 14:49 UTC, philippewarren commented on face_cropping/launch/face_cropping.launch
> +    <node if="true" name="$(arg name)" pkg="face_cropping" type="face_cropping" respawn="true" output="$(arg output)">
Should this `if="true"` be removed or changed to an `$(arg ...)` evaluation?

2022-11-30 14:49 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +        m_noDetectionCounter < m_parameters.refreshRate() * m_parameters.secondsWithoutDetection() &&
Maybe make a named function for this long condition that appears multiple times?

2022-11-30 14:49 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +        std::tuple<int, std::vector<std::tuple<int, cv::Rect>>> faceVector = m_lastDetectedFaces[i];
A type alias for this might be useful, too. Or only for this, then the vector one just becomes a `std::vector<this_type_alias>`?

2022-11-30 14:49 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +        for (std::tuple<int, std::vector<std::tuple<int, cv::Rect>>>& otherFaceVector : otherFaceVectors)
Use `auto` (or the type alias, but `auto` is cleaner in my opinion)
[ES.11](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es11-use-auto-to-avoid-redundant-repetition-of-type-names)

2022-11-30 14:49 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +    for (detectionVector::iterator it = m_lastDetectedFaces.begin(); it != m_lastDetectedFaces.end(); it++)
Use range-based for loop

2022-11-30 14:49 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +                [this](std::tuple<int, cv::Rect>& item)
Use `auto&` in lambda parameters

2022-11-30 14:49 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +                std::end(get<1>(*it)),
Lots of `get<>`: replace `std::tuple` with a struct for better readability?

2022-11-30 14:49 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +            [this](std::tuple<int, std::vector<std::tuple<int, cv::Rect>>>& item) { return get<1>(item).size() == 0; }),
Use `auto&` in lambda parameters

2022-11-30 14:49 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +            for (detectionVector::iterator it = m_lastDetectedFaces.begin(); it != m_lastDetectedFaces.end(); it++)
Use range-based for loop

2022-11-30 14:49 UTC, philippewarren commented on opentera_webrtc_robot_gui/src/MainWindow.cpp
> +    m_ui->cropFaceButton->setCheckable(true);
This can be set in the `.ui` file. But would this be better?

2022-11-30 15:03 UTC, joli-1801 commented on README.md
> -$sudo apt-get install nodejs ros-noetic-turtlebot3 ros-noetic-turtlebot3-gazebo $ros-noetic-dwa-local-planner ros-noetic-rtabmap-ros
The "$" was already there, so I just left it, but I can remove it, since it blocks the installation

2022-11-30 15:15 UTC, joli-1801 commented on face_cropping/launch/face_cropping.launch
> +    <node if="true" name="$(arg name)" pkg="face_cropping" type="face_cropping" respawn="true" output="$(arg output)">
Yes I'll remove it, I forgot it, it was used to debug

2022-11-30 15:51 UTC, mamaheux requested changes

2022-11-30 15:51 UTC, mamaheux commented on face_cropping/src/FaceCropper.cpp
> +        }
Use static_cast\<int\>(trunc(newWidth)) instead?

2022-11-30 16:11 UTC, mamaheux commented on face_cropping/src/FaceCropper.cpp
> +    header.stamp = ros::Time::now();
Can you use the input image header instead?

2022-11-30 16:42 UTC, joli-1801 commented on opentera_webrtc_robot_gui/src/MainWindow.cpp
> +    m_ui->cropFaceButton->setCheckable(true);
Because of the way we use resources for the icons, I think setting the icons in the code is a better idea. The text part is also necessary since in the `.ui` we use the text to show the button names. But setting the button as checkable in the `.ui` directly is a good idea.

2022-11-30 17:55 UTC, joli-1801 commented on face_cropping/include/face_cropping/MathUtils.h
> +    }
Since in this case we want the closest integer to a float that is dividable by a float, is that method possible? Say we have an  `a` of 135 and a `b` of 1.3, this method would result with 135.2 instead of 130. I tried rounding up and down values to try and arrive at a good value and it didn't work. So can this be done without some sort of recursive element to check if the resulting value is an integer?

2022-11-30 18:05 UTC, mamaheux commented on face_cropping/include/face_cropping/MathUtils.h
> +    }
I don't have any clue how to do that with a float, so it's ok.

2022-11-30 18:17 UTC, joli-1801 commented on face_cropping/include/face_cropping/MathUtils.h
> +    }
The standard is C++11

2022-11-30 18:41 UTC, mamaheux commented on face_cropping/include/face_cropping/MathUtils.h
> +    }
Can you use c++17?

2022-11-30 19:30 UTC, joli-1801 commented on face_cropping/include/face_cropping/MathUtils.h
> +    }
It doesn't seem like it, I changed the c++ version in the CMakeLists.txt and it didn't work. It also doesn't seem to be supported by ros [](https://answers.ros.org/question/341313/what-happens-if-i-use-c-17-features-in-my-ros-nodes/).

2022-11-30 19:44 UTC, joli-1801 commented on face_cropping/include/face_cropping/FaceCropper.h
> +    using detectionVector = std::vector<std::tuple<int, std::vector<std::tuple<int, cv::Rect>>>>;
Because of the change from `std::tuple` to `struct` I no longer have the type

2022-11-30 19:47 UTC, joli-1801 commented on face_cropping/src/FaceCropper.cpp
> +        std::tuple<int, std::vector<std::tuple<int, cv::Rect>>> faceVector = m_lastDetectedFaces[i];
With the change from `std::tuple` to `struct` it's now `FaceVector` and `std::vector<FaceVector>`

2022-11-30 20:10 UTC, mamaheux commented on face_cropping/include/face_cropping/MathUtils.h
> +    }
In T-Top, I have used C++17 and it works. If you want to keep c++11, it's fine too.

https://github.com/introlab/t-top/blob/main/ros/utils/recorders/CMakeLists.txt#L5-L6

2022-11-30 20:36 UTC, joli-1801 commented on face_cropping/include/face_cropping/MathUtils.h
> +    }
I've changed it to c++17 and removed the `getGCD` function

2022-11-30 22:00 UTC, philippewarren requested changes

2022-11-30 22:11 UTC, philippewarren requested changes

2022-11-30 22:11 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +            struct DetectionFrame newDetection = {m_frameCounter, detectedFace};
The struct keyword is not needed

2022-11-30 22:11 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +            struct FaceVector newFace = {m_frameCounter, newVect};
the struct keyword is not needed

2022-11-30 22:11 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +            m_lastDetectedFaces.emplace_back(newFace);
`emplace_back` can receive the arguments directly, it will construct the object in place and save a copy

2022-11-30 22:11 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +            newVect.emplace_back(newDetection);
`emplace_back` can receive the arguments directly, it will construct the object in place and save a copy

2022-11-30 22:12 UTC, philippewarren commented on opentera_webrtc_robot_gui/src/MainWindow.cpp
> +    m_ui->cropFaceButton->setCheckable(true);
Good points!

2022-11-30 22:22 UTC, philippewarren commented on face_cropping/include/face_cropping/MathUtils.h
> +    }
To add to this, I found [this great answer by a GCC developer](https://stackoverflow.com/a/49119902) stating that ABI compatibility is guaranteed in GCC, even across standards IF everything is compiled with the same version of GCC.
Meaning, if we compile with the default GCC on Ubuntu 20.04, which is also the GCC that was used to compile the ROS libraries (presumably), we should be fine using any standard we want.

2022-11-30 23:37 UTC, mamaheux requested changes

2022-11-30 23:37 UTC, mamaheux commented on face_cropping/src/FaceCropper.cpp
> +        }
I am not sure why you are using round here. I understand that you don't want the width to be 0. 
Is the following code equivalent?
```suggestion
        if (newWidth >= 1.f)
        {
            r.width = newWidth;
        }
        else
        {
            r.width = 1;
        }
```

2022-11-30 23:37 UTC, mamaheux commented on face_cropping/src/FaceCropper.cpp
> +        }
Same thing here
```suggestion
        if (newHeight >= 1.f)
        {
            r.height = newHeight;
        }
        else
        {
            r.height = 1;
        }
```

2022-11-30 23:37 UTC, mamaheux commented on face_cropping/src/FaceCropper.cpp
> +                        cv::rectangle(frame, detectedFace, cv::Scalar(0, 255, 0), 2);
Can you define constexpr for all colors, so we can change them easily.

2022-12-01 15:52 UTC, joli-1801 commented on face_cropping/src/FaceCropper.cpp
> +        }
Yes, it would and is the `static_cast` necessary, would an implicit conversion do the same thing?

2022-12-01 16:29 UTC, mamaheux commented on face_cropping/src/FaceCropper.cpp
> +        }
Without static_cast, you would get a warning.

2022-12-01 16:32 UTC, joli-1801 commented on face_cropping/src/FaceCropper.cpp
> +                        cv::rectangle(frame, detectedFace, cv::Scalar(0, 255, 0), 2);
Yes, but since `cv::Scalar` isn't a literal type I can't use it as a constexpr, would simply using an array as the constexpr and calling for example `cv::Scalar(GREEN[0], GREEN[1], GREEN[2])` be ok, or should I use something like a member variable that is a cv::Scalar?

2022-12-01 17:02 UTC, joli-1801 commented on face_cropping/src/FaceCropper.cpp
> +        cv_bridge::CvImage(header, sensor_msgs::image_encodings::RGB8, frame).toImageMsg();
I've removed this method for another comment, but I think it is in `peerFrameReceivedCallback`, should I make `newPeerImage` a member variable instead?

2022-12-01 17:57 UTC, joli-1801 commented on face_cropping/src/FaceCropper.cpp
> +                        cv::rectangle(frame, detectedFace, cv::Scalar(0, 255, 0), 2);
I ended up using a const cv::Scalar instead, as you suggested

2022-12-02 20:21 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +        cv_bridge::CvImage(header, sensor_msgs::image_encodings::RGB8, frame).toImageMsg();
If the returned pointer is a shared_ptr, this should be fine. We should validate that.

2022-12-02 20:38 UTC, philippewarren requested changes

2022-12-02 20:38 UTC, philippewarren commented on face_cropping/include/face_cropping/FaceCropper.h
> +    const cv::Scalar RED = cv::Scalar(255, 0, 0);
These might need to be declared `inline`. This should be tested by including this `.h` in two different compilation units.
Or, better yet, these should be moved in the CPP file as they are only used there.
They should also be better named, based on their usage in the application.

2022-12-02 20:38 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +        eraseRemoveIf<DetectionFrame>(
You probably don't need to explicitly specify the template argument here, it should be deduced automatically.

2022-12-02 20:38 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +    eraseRemoveIf<FaceVector>(m_lastDetectedFaces, [this](FaceVector& item) { return (item).face.size() == 0; });
You probably don't need to explicitly specify the template argument here, it should be deduced automatically.

2022-12-05 13:48 UTC, joli-1801 commented on face_cropping/include/face_cropping/FaceCropper.h
> +    const cv::Scalar RED = cv::Scalar(255, 0, 0);
I've moved them to the cpp file, renamed them and made them inline

2022-12-05 13:49 UTC, joli-1801 commented on face_cropping/src/FaceCropper.cpp
> +        eraseRemoveIf<DetectionFrame>(
Removing the template creates a `no matching function` error during compilation

2022-12-05 13:50 UTC, joli-1801 commented on face_cropping/src/FaceCropper.cpp
> +    eraseRemoveIf<FaceVector>(m_lastDetectedFaces, [this](FaceVector& item) { return (item).face.size() == 0; });
Removing the template creates a `no matching function` error during compilation

2022-12-05 14:47 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +inline const cv::Scalar BOUNDING_BOX_RED = cv::Scalar(255, 0, 0);
They don't need to be inline if in the cpp file.
Also, I think a name that describes what the color shows would be better than simply adding the `BOUNDING_BOX` prefix. Like for instance, if one is used to faces facing the camera, and the other one for heads that are not facing the camera, they could be named `BOUNDING_BOX_FACING_CAMERA` and `BOUNDING_BOX_NOT_FACING_CAMERA` or something.

2022-12-05 14:47 UTC, philippewarren commented on face_cropping/src/FaceCropper.cpp
> +            m_lastDetectedFaces.emplace_back(FaceVector{m_frameCounter, newVect});
Doesn't it work if you remove `DetectionFrame` and `FaceVector` here? It should, as `emplace_back` should just pass the arguments in the call to the underlying constructor.

2022-12-05 15:20 UTC, joli-1801 commented on face_cropping/src/FaceCropper.cpp
> +        cv_bridge::CvImage(header, sensor_msgs::image_encodings::RGB8, frame).toImageMsg();
In the cv bridge documentation [Converting between ROS images and OpenCV images (C++)](http://wiki.ros.org/cv_bridge/Tutorials/UsingCvBridgeToConvertBetweenROSImagesAndOpenCVImages) the Image pointers are shared, so I think it's safe to assume that it is, even if they don't specifiy it in the toImageMsg() documentation. By digging a bit further I also found that they use it this way in their examples [Publishing images](http://wiki.ros.org/image_transport/Tutorials/PublishingImages)

2022-12-05 15:36 UTC, joli-1801 commented on face_cropping/src/FaceCropper.cpp
> +            m_lastDetectedFaces.emplace_back(FaceVector{m_frameCounter, newVect});
No, I did try without the struct name, and it creates a `no matching function` error

2022-12-06 16:01 UTC, mamaheux approved these changes

2022-12-06 18:26 UTC, doumdi approved these changes

2022-12-06 18:28 UTC, merged