Add calls between robots and closing session from the robot gui
introlab/opentera-webrtc-ros pull request #63
Opened 2022-12-13 19:45 UTC by joli-1801

2022-12-13 20:21 UTC, doumdi requested changes

2022-12-13 20:21 UTC, doumdi commented on opentera_webrtc_ros/include/RosWebRTCBridge.h
> +            for (auto i = 0; i < msg->join_session_events.size(); i++)
This loop seems useless, just check size of msg->join_session_events and update the m_hasMultipleDevices flag.

2022-12-13 20:21 UTC, doumdi commented on opentera_webrtc_ros/include/RosWebRTCBridge.h
> +            m_hasMultipleDevices = false;
Is the m_hasMultipleDevices flag really useful, maybe just always callAll() when a new client is not connected?

2022-12-13 20:25 UTC, doumdi commented on opentera_webrtc_ros/include/RosWebRTCBridge.h
> +            for (auto i = 0; i < msg->join_session_events.size(); i++)
See comment below on m_hasMultipleDevices

2022-12-13 20:25 UTC, doumdi commented on opentera_webrtc_ros/include/RosWebRTCBridge.h
> +            m_hasMultipleDevices = false;
Why clear the flag ?

2022-12-13 22:11 UTC, joli-1801 commented on opentera_webrtc_ros/include/RosWebRTCBridge.h
> +            m_hasMultipleDevices = false;
It was to narrow down the cases when we used callAll() to make sure that we wouldn't call it in cases where for some reason we'd want a client not to be connected. If we always want the clients to be connected we shouldn't run into any issues, so I'll remove it.

2022-12-14 13:36 UTC, joli-1801 commented on opentera_webrtc_ros/include/RosWebRTCBridge.h
> +            for (auto i = 0; i < msg->join_session_events.size(); i++)
I've removed the loop, since I removed the flag

2022-12-14 14:34 UTC, philippewarren requested changes

2022-12-14 14:34 UTC, philippewarren commented on opentera_client_ros/scripts/opentera_client_ros.py
> +                            print('Send stop session failed')
Use ROS logging facilities instead of `print` everywhere?

2022-12-14 14:34 UTC, philippewarren commented on opentera_client_ros/scripts/opentera_client_ros.py
> +            print('Action not implemented')
```suggestion
            raise NotImplementedError(f"Action {action} not implemented")
```

2022-12-14 14:34 UTC, philippewarren commented on opentera_client_ros/scripts/opentera_client_ros.py
> +        async with aiohttp.ClientSession() as self.__client:
I didn't know you could bind the result of a `with` to an instance member! But what happens when the `with` is exited? `self.__client` is then bound to a dead client? Is this checked consistently where `self.__client` is used anywhere else?

2022-12-14 14:34 UTC, philippewarren commented on opentera_webrtc_ros/include/RosWebRTCBridge.h
>                     ", isConnected: " + (client.isConnected() ? "true" : "false");
```suggestion
            ROS_INFO_STREAM("\tid: " << client.id() << ", name: " << client.name() <<
                   ", isConnected: " << std::boolalpha << client.isConnected() << "\n");
```

2022-12-14 14:34 UTC, philippewarren commented on opentera_webrtc_ros/include/RosWebRTCBridge.h
>          std::string log = nodeName + " --> Signaling on room clients changed:";
```suggestion
        ROS_INFO_STREAM(nodeName << " --> Signaling on room clients changed:\n");
```

2022-12-14 14:34 UTC, philippewarren commented on opentera_webrtc_ros/include/RosWebRTCBridge.h
> +        bool clientNotConnected = false;
Rename to better explain the usage. `allClientsConnected`? (with `= true` default)

2022-12-14 14:34 UTC, philippewarren commented on opentera_webrtc_ros/include/RosWebRTCBridge.h
> +            }
```suggestion
            allClientsConnected &= client.isConnected();
```

2022-12-14 14:34 UTC, philippewarren commented on opentera_webrtc_ros/include/RosWebRTCBridge.h
> +            m_signalingClient->callAll();
```suggestion
        if (!allClientsConnected)
        {
            m_signalingClient->callAll();
```

2022-12-14 16:39 UTC, joli-1801 commented on opentera_client_ros/scripts/opentera_client_ros.py
> +        async with aiohttp.ClientSession() as self.__client:
At the moment when we exit the with, the node stops, so it shouldn't be a problem

2022-12-14 17:01 UTC, doumdi approved these changes

2022-12-14 17:02 UTC, merged