Yunet like dnn face cropping
introlab/opentera-webrtc-ros pull request #71
Opened 2023-08-18 02:14 UTC by mamaheux

2023-08-20 18:56 UTC, philippewarren requested changes
Most notably in Python:
- Use `pathlib` to gain expressiveness compared to `os.path`
- Use `Enum` instead of magic strings
- Use one form of `super()` everywhere
- Using typehints would have been a good idea I think, but I don't recommend adding them at this point. Adding them from the start, as we code is usually way easier.

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/OpencvFaceDetector.cpp
> +    float scale = std::min(float(m_maxWidth) / float(bgrImage.cols), float(m_maxHeight) / float(bgrImage.rows));
Per [ES.49 in the C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es49-if-you-must-use-a-cast-use-a-named-cast), avoid function-style casts and prefer `static_cast` or `type{value}` casts, which are non-narrowing.

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/OpencvFaceDetector.cpp
> +          getPackagePath() + "/models/haarcascade_frontalface_default.xml")
These magic string literals could be a constexpr static member of the class or something.

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/OpencvFaceDetector.cpp
> +          getPackagePath() + "/models/lbpcascade_frontalface_improved.xml")
These magic string literals could be a constexpr static member of the class or something.

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/TorchFaceDetector.cpp
> +    float scale = std::min(float(m_maxWidth) / float(bgrImage.cols), float(m_maxHeight) / float(bgrImage.rows));
Per [ES.49 in the C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es49-if-you-must-use-a-cast-use-a-named-cast), avoid function-style casts and prefer `static_cast` or `type{value}` casts, which are non-narrowing.

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/TorchFaceDetector.cpp
> +    m_inputTensor.mul_(0.00392156862f);  // Div 255
Replace comment with `constexpr static float ONE_OVER_255 = 1.0f / 255.0f; m_inputTensor.mul_(ONE_OVER_255);`?

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/TorchFaceDetector.cpp
> +          getPackagePath() + "/models/small_yunet_0.25_silu_160.pt")
Magic string literal could be a constexpr static member of the class?

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/TorchFaceDetector.cpp
> +          getPackagePath() + "/models/small_yunet_0.25_silu_320.pt")
Magic string literal could be a constexpr static member of the class?

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/TorchFaceDetector.cpp
> +          getPackagePath() + "/models/small_yunet_0.25_silu_640.pt")
Magic string literal could be a constexpr static member of the class?

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/TorchFaceDetector.cpp
> +          getPackagePath() + "/models/small_yunet_0.5_silu_160.pt")
Magic string literal could be a constexpr static member of the class?

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/TorchFaceDetector.cpp
> +          getPackagePath() + "/models/small_yunet_0.5_silu_320.pt")
Magic string literal could be a constexpr static member of the class?

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/TorchFaceDetector.cpp
> +          getPackagePath() + "/models/small_yunet_0.5_silu_640.pt")
Magic string literal could be a constexpr static member of the class?

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/face_cropping_node.cpp
> +        return -1;
Print to ROS_ERROR before quitting?

2023-08-20 18:56 UTC, philippewarren commented on face_cropping/src/face_cropping_webrtc_node.cpp
> +        return -1;
Print to ROS_ERROR before quitting?

2023-08-29 15:14 UTC, mamaheux commented on face_cropping/dnn_training/metrics/loss_accuracy_learning_curves.py
> +        ax2.set_ylabel(u'Accuracy')
I have warnings indicating that the fields do not exist when I do that.

2023-08-29 15:17 UTC, mamaheux commented on face_cropping/launch/face_cropping.launch
> +    <arg name="use_gpu_if_available" default="false"/>
No because the RAM increase by 2 GB when using the GPU.

Since the networks are very fast on the CPU, I think it's ok to default to the CPU.

2023-08-29 15:33 UTC, mamaheux commented on face_cropping/dnn_training/mmdet/sim_ota_assigner.py
> +# Copyright (c) OpenMMLab. All rights reserved.
Yes, the lib is  Apache-2.0 license.

2023-08-29 15:33 UTC, mamaheux commented on face_cropping/dnn_training/mmdet/util_random.py
> +# Copyright (c) OpenMMLab. All rights reserved.
Yes, the lib is  Apache-2.0 license.

2023-08-29 15:33 UTC, mamaheux commented on face_cropping/dnn_training/mmdet/iou2d_calculator.py
> +# Copyright (c) OpenMMLab. All rights reserved.
Yes, the lib is  Apache-2.0 license.

2023-08-29 15:40 UTC, mamaheux commented on face_cropping/dnn_training/metrics/average_precision_metric.py
> +        self._false_positives = []
I have warnings indicating that the fields do not exist when I do that.

2023-08-29 15:40 UTC, mamaheux commented on face_cropping/dnn_training/metrics/loss_average_precision_learning_curves.py
> +        self._validation_ap_values = []
I have warnings indicating that the fields do not exist when I do that.

2023-08-29 15:49 UTC, mamaheux commented on face_cropping/dnn_training/criterions/single_class_detection_loss.py
> +            raise ValueError('Invalid bbox_loss_type')
I use the strings since other DNN repos use that even if enums are better.

2023-08-29 15:49 UTC, mamaheux commented on face_cropping/dnn_training/criterions/single_class_detection_loss.py
> +            raise ValueError('Invalid bbox_loss_type')
I use the strings since other DNN repos use that even if enums are better.

2023-08-29 15:50 UTC, mamaheux commented on face_cropping/dnn_training/datasets/head_detection_open_images.py
> +            raise ValueError('Invalid split')
I use the strings since other DNN repos use that even if enums are better.

2023-08-29 15:50 UTC, mamaheux commented on face_cropping/dnn_training/evaluate_opencv_face_detector.py
> +        raise ValueError('Invalid dataset type')
I use the strings since other DNN repos use that even if enums are better.

2023-08-29 15:54 UTC, mamaheux commented on face_cropping/dnn_training/datasets/classification_image_net.py
> +    return filename.endswith('.JPEG') or filename.endswith('.JPG')
Yes, it's slower. There are 14 million images so the impact is big.

2023-08-29 16:01 UTC, mamaheux commented on face_cropping/dnn_training/datasets/detection_mosaic_dataset.py
> +        return (image is not None and
mosaic_image is never None.

2023-08-29 18:44 UTC, mamaheux commented on face_cropping/dnn_training/datasets/head_detection_open_images.py
> +            raise ValueError('Invalid rotation')
I don't think it is necessary since this is only inside the class.

2023-08-29 18:50 UTC, mamaheux commented on face_cropping/dnn_training/test_detector.py
> +    video_capture.release()
__enter__ and __exit__ is not implemented for cv2.VideoCapture.

2023-08-29 19:23 UTC, philippewarren requested changes

2023-08-29 19:23 UTC, philippewarren commented on face_cropping/dnn_training/criterions/single_class_detection_loss.py
> +    def __init__(self,):
Should the trailing comma be there?

2023-08-29 19:23 UTC, philippewarren commented on face_cropping/dnn_training/trainers/distillation_trainer.py
> +        torch.save(self._student_model.state_dict(), self._output_path / 'model_checkpoint_epoch_{}.pth'.format(epoch))
f-string instead of `.format`?

2023-08-29 19:23 UTC, philippewarren commented on face_cropping/dnn_training/utils/path.py
> +        return Path(path)
The `Path` constructor can take a Path and return a Path (`Path("/bin") == Path(Path("/bin"))`.
But if your goal is to keep identity (wether`Path("/bin") is Path(Path("/bin"))`), I'm not sure if it is guaranteed.

Also, something I've learned with Path: if you need to expand `~` to the user HOME folder, you need to use the`expanduser()` method of Path, which returns a new Path object with the `~` expanded. I usually have a Path-creating function that does that everytime.
Not sure if this kind of paths are used in this case, but I'm adding this in case it could be useful.

2023-08-29 19:38 UTC, mamaheux commented on face_cropping/dnn_training/utils/path.py
> +        return Path(path)
I didn't know for  (Path("/bin") == Path(Path("/bin")).

2023-08-29 20:11 UTC, philippewarren approved these changes

2023-08-29 20:36 UTC, merged