Fix READMEs for ROS2
introlab/opentera-webrtc-ros pull request #84
Opened 2024-07-23 18:03 UTC by philippewarren

2024-07-23 20:27 UTC, doumdi requested changes
sensor_msgs  instead of sensor_msg ?

2024-07-23 20:27 UTC, doumdi commented on opentera_webrtc_ros/README.md
> +- ros_image : `sensor_msg/Image`
sensor_msgs ?

2024-07-23 20:43 UTC, philippewarren commented on opentera_webrtc_ros/README.md
> +- ros_image : `sensor_msg/Image`
Good catch!

2024-07-25 17:37 UTC, doumdi approved these changes

2024-07-25 17:40 UTC, merged